version: '3'
services:
  lucee:
    container_name: lucee-box
    build:
      context: ./config
      dockerfile: Dockerfile
<<<<<<< HEAD
    image: oscaralvarez/lucee-commandbox
    network_mode: bridge
#    links:
#      - mysql
    ports:
      - "8888:8888"
#    volumes:
#      - "~/projects/commandbox-cfconfig/commands:/root/.Commandbox:rw"
=======

    ports:
      - "8888:8888"

>>>>>>> 1870bbec3d04cb82af0d0088df50e24cea0c5c3c
